// Shared language toggle and translation utility for standalone pages
(function () {
  const translations = {
    en: {
      // Navigation
      'nav-home': 'Home',
      'nav-crop-rec': 'Crop Recommendation',
      'nav-disease': 'Disease Detection',
      'nav-about': 'About',
      'nav-contact': 'Contact',
      'nav-helplines': 'Helplines',
      'nav-schemes': 'Govt Schemes',
      'nav-dashboard': 'Dashboard',
      'nav-soil': 'Soil Testing Kit',
      
      // Hero Section
      'hero-title': 'Smart Farming Powered by AI',
      'hero-subtitle': 'Revolutionizing agriculture with intelligent crop recommendations and disease detection',
      'cta-button': 'Get Crop Advice 🌾',
      'soil-testing-button': 'Soil Testing Kit 🧪',
      
      // Stats Section
      'farmers-helped': 'Farmers Helped',
      'crop-varieties': 'Crop Varieties',
      'accuracy-rate': 'Accuracy Rate',
      'ai-support': 'AI Support',
      
      // Features Section
      'features-title': 'Our AI-Powered Solutions',
      'features-subtitle': 'Empowering farmers with cutting-edge technology for better yields and sustainable farming',
      
      // Feature Cards
      'feature-crop-rec': 'Crop Recommendation',
      'feature-crop-rec-desc': 'Get AI-powered crop suggestions based on your soil parameters, weather conditions, and regional data for optimal yields.',
      'explore-feature': 'Explore Feature',
      'feature-disease-detection': 'Disease Detection',
      'feature-disease-desc': 'Upload plant images for instant disease identification using advanced computer vision and get treatment recommendations.',
      'detect-disease': 'Detect Disease',
      'feature-pest-detection': 'Pest Detection',
      'feature-pest-desc': 'Identify common pests affecting your crops with image recognition and get organic and chemical treatment solutions.',
      'feature-market-prices': 'Market Prices',
      'feature-market-prices-desc': 'Real-time market prices for various crops to help you get the best deal for your produce.',
      'check-prices': 'Check Prices',
      'feature-profit-loss': 'Profit/Loss',
      'feature-profit-loss-desc': 'Track your farming expenses and income to calculate profit/loss and optimize your farming business.',
      'calculate-now': 'Calculate Now',
      'feature-ai-assistant': 'AI Assistant',
      'feature-ai-assistant-desc': 'Get instant answers to all your farming questions with our 24/7 AI-powered agricultural assistant.',
      'chat-now': 'Chat Now',
      'feature-community': 'Community',
      'feature-community-desc': 'Connect with fellow farmers, share experiences, and get expert advice in our farming community.',
      'join-community': 'Join Community',
      'feature-crop-calendar': 'Crop Calendar',
      'feature-crop-calendar-desc': 'Plan your farming activities with our crop calendar featuring optimal sowing and harvesting times.',
      'view-calendar': 'View Calendar',
      'feature-learning-hub': 'Learning Hub',
      'feature-learning-hub-desc': 'Access farming guides, tutorials, and best practices to enhance your agricultural knowledge.',
      'start-learning': 'Start Learning',
      'feature-soil-testing': 'Soil Testing',
      'feature-soil-testing-desc': 'Get detailed soil analysis and recommendations to improve soil health and crop productivity.',
      'test-your-soil': 'Test Your Soil',
      'feature-fertilizer-guide': 'Fertilizer Guide',
      'feature-fertilizer-guide-desc': 'Learn about different types of fertilizers, their uses, and application methods for various crops.',
      'view-guide': 'View Guide',
      'feature-govt-schemes': 'Govt Schemes',
      'feature-govt-schemes-desc': 'Discover and apply for government agricultural schemes and subsidies available for farmers.',
      'view-schemes': 'View Schemes',
      'feature-helplines': 'Helplines',
      'feature-helplines-desc': 'Access important government and agricultural helpline numbers for immediate assistance and support.',
      'view-helplines': 'View Helplines',
      
      // How It Works Section
      'how-it-works-title': 'How AgriSense Works',
      'how-it-works-subtitle': 'Simple steps to transform your farming with AI technology',
      'step-1-title': '1. Input Your Data',
      'step-1-desc': 'Enter details about your farm location, soil type, and other relevant parameters.',
      'step-2-title': '2. Get AI Analysis',
      'step-2-desc': 'Our advanced algorithms analyze your data to provide personalized recommendations.',
      'step-3-title': '3. Get Results',
      'step-3-desc': 'Receive personalized recommendations instantly.',
      'step-4-title': '4. Grow Better',
      'step-4-desc': 'Implement insights and watch your yields improve.',
      
      // Testimonials Section
      'testimonials-title': 'What Farmers Say',
      'testimonials-subtitle': 'Hear from farmers who have transformed their farming with AgriSense',
      'testimonial-1': '\"AgriSense helped me increase my crop yield by 30% with their smart recommendations. The disease detection feature saved my entire tomato crop!\"',
      'testimonial-2': '\"The market price updates and profit/loss calculator have been game-changers for my farming business. I can now make better decisions.\"',
      'testimonial-3': '\"As a new farmer, the learning resources and community support have been invaluable. The AI assistant answers all my questions instantly.\"',
      
      // CTA Section
      'cta-title': 'Ready to Transform Your Farming?',
      'cta-subtitle': 'Join thousands of farmers who are already benefiting from AI-powered agricultural insights.',
      'get-started-button': 'Start Now - It\'s Free! 🚀',
      'learn-more-button': 'Learn More',
      
      // Footer
      'footer-title': 'AgriSense',
      'footer-tagline': 'Empowering farmers with AI-powered agricultural solutions for better yields and sustainable farming.',
      'quick-links': 'Quick Links',
      'contact-us': 'Contact Us',
      'email': 'Email: support@agrisense.com',
      'phone': 'Phone: +91 98765 43210',
      'address': 'Address: 123 Farm Road, Agri Valley, India',
      'copyright': '© 2023 AgriSense. All rights reserved.',
      'privacy-policy': 'Privacy Policy',
      'terms-of-service': 'Terms of Service',
      
      // Common
      'home-title': 'AgriSense - Home',
      'offline-banner': '🌐 Works Partially Offline in Low Connectivity Regions',
      'site-name': 'AgriSense',
      'site-tagline': 'AI Crop Recommendation System',
      
      // Helplines Page
      'helpline-title': 'Farmer Helpline Numbers',
      'helpline-subtitle': 'Find government helpline numbers for farmers across different states',
      'helpline-search': 'Search by state or number...',
      'helpline-kisan': 'Kisan Call Center',
      'helpline-state': 'State Agriculture Department',
      'helpline-select-state': 'Select a state...',
      'helpline-all-states': 'All States',
      'community-hero-title': 'Join Our Plant Lovers Community',
      'start-discussion': 'Start New Discussion',
      'forum-title': "Farmer's Discussion Forum",
      'new-post': 'New Post',
      'comments': 'comments',
      'likes': 'likes',
      'share': 'Share',
      'view-details': 'View Details',
      'add-comment': 'Add a comment',
      'write-comment': 'Write a comment...',
      'translate': 'Translate',
      'translating': 'Translating...',
      'show-original': 'Show Original',
      'hero-title': 'Smart Farming Powered by AI',
      'hero-subtitle': 'Revolutionizing agriculture with intelligent crop recommendations and disease detection',
      'cta-button': 'Get Crop Advice 🌾',
      'features-title': 'Our AI-Powered Solutions',
      'features-subtitle': 'Empowering farmers with cutting-edge technology for better yields and sustainable farming',
      'crop-rec-title': 'AI Crop Recommendation',
      'disease-title': 'Plant Disease Detection',
      'dashboard-title': 'Agricultural Dashboard',
      'contact-title': 'Contact Us',
      'about-title': 'About AgriSense',
      'soil-hero-title': 'Affordable Soil Testing Kit',
      'soil-hero-subtitle': 'Know your soil better for smarter farming decisions',
      'soil-cta-button': 'Request Your Kit Now 📦',
      'soil-why-title': 'Why Soil Testing Matters?',
      'soil-whats-included': "What's Included in the Kit?",
      'soil-request-title': 'Request Your Soil Testing Kit',
      'soil-request-subtitle': "Fill out the form below and we'll deliver the kit to your doorstep within 3-5 business days",
      
      // Profit & Loss Calculator
      'profit-loss-title': 'Profit & Loss Calculator',
      'profit-loss-subtitle': 'Calculate your farming profits, analyze expenses, and optimize your agricultural business for better returns',
      'enter-details': 'Enter Your Farming Details',
      'basic-info': 'Basic Information',
      'crop-name': 'Crop Name',
      'land-area': 'Land Area (acres)',
      'costs': 'Costs',
      'add-cost': 'Add Cost',
      'cost-name': 'Cost Name',
      'amount': 'Amount',
      'total-costs': 'Total Costs',
      'revenue': 'Revenue',
      'add-revenue': 'Add Revenue',
      'revenue-name': 'Revenue Source',
      'total-revenue': 'Total Revenue',
      'calculate': 'Calculate',
      'reset': 'Reset',
      'results': 'Results',
      'profit': 'Profit',
      'loss': 'Loss',
      'break-even': 'Break Even',
      'profit-message': 'Great work! You\'re making a profit of',
      'loss-message': 'Consider reviewing your expenses. Your current loss is',
      'break-even-message': 'Your revenue equals your costs. Consider ways to increase your profit margin.',
      'per-acre': 'per acre',
      'save-to-dashboard': 'Save to Dashboard',
      'print-report': 'Print Report',
      'saved-toast': 'Saved to your dashboard!',
      'error-toast': 'Please fill in all required fields'
    },
    hi: {
      // Navigation
      'nav-home': 'होम',
      'nav-crop-rec': 'फसल सिफारिश',
      'nav-disease': 'रोग निदान',
      'nav-about': 'के बारे में',
      'nav-contact': 'संपर्क',
      'nav-helplines': 'हेल्पलाइन',
      'nav-schemes': 'सरकारी योजनाएं',
      'nav-dashboard': 'डैशबोर्ड',
      'nav-soil': 'मिट्टी परीक्षण किट',
      
      // Hero Section
      'hero-title': 'एआई द्वारा संचालित स्मार्ट खेती',
      'hero-subtitle': 'बुद्धिमान फसल सिफारिशों और रोग निदान के साथ कृषि में क्रांति',
      'cta-button': 'फसल सलाह प्राप्त करें 🌾',
      'soil-testing-button': 'मिट्टी परीक्षण किट 🧪',
      
      // Stats Section
      'farmers-helped': 'किसानों की मदद की गई',
      'crop-varieties': 'फसल किस्में',
      'accuracy-rate': 'सटीकता दर',
      'ai-support': 'एआई सहायता',
      
      // Features Section
      'features-title': 'हमारे एआई-संचालित समाधान',
      'features-subtitle': 'बेहतर उत्पादन और टिकाऊ खेती के लिए अत्याधुनिक तकनीक से किसानों को सशक्त बनाना',
      
      // Feature Cards
      'feature-crop-rec': 'फसल सिफारिश',
      'feature-crop-rec-desc': 'अपने मिट्टी के पैरामीटर, मौसम की स्थिति और क्षेत्रीय डेटा के आधार पर एआई-संचालित फसल सुझाव प्राप्त करें।',
      'explore-feature': 'फीचर एक्सप्लोर करें',
      'feature-disease-detection': 'रोग पहचान',
      'feature-disease-desc': 'उन्नत कंप्यूटर विज़न का उपयोग करके तत्काल रोग पहचान के लिए पौधों की छवियां अपलोड करें और उपचार सिफारिशें प्राप्त करें।',
      'detect-disease': 'रोग का पता लगाएं',
      'feature-pest-detection': 'कीट पहचान',
      'feature-pest-desc': 'छवि पहचान के साथ अपनी फसलों को प्रभावित करने वाले सामान्य कीटों की पहचान करें और जैविक और रासायनिक उपचार समाधान प्राप्त करें।',
      'feature-market-prices': 'बाजार मूल्य',
      'feature-market-prices-desc': 'विभिन्न फसलों के लिए रीयल-टाइम बाजार मूल्य जो आपको अपनी उपज का सर्वोत्तम मूल्य पाने में मदद करेंगे।',
      'check-prices': 'मूल्य जांचें',
      'feature-profit-loss': 'लाभ/हानि',
      'feature-profit-loss-desc': 'अपने कृषि व्यवसाय को अनुकूलित करने के लिए अपने खेती के खर्च और आय को ट्रैक करें और लाभ/हानि की गणना करें।',
      'calculate-now': 'अभी गणना करें',
      'feature-ai-assistant': 'एआई सहायक',
      'feature-ai-assistant-desc': 'हमारे 24/7 एआई-संचालित कृषि सहायक के साथ अपने सभी कृषि प्रश्नों के तत्काल उत्तर प्राप्त करें।',
      'chat-now': 'अभी चैट करें',
      'feature-community': 'समुदाय',
      'feature-community-desc': 'हमारे कृषि समुदाय में अन्य किसानों से जुड़ें, अनुभव साझा करें और विशेषज्ञ सलाह प्राप्त करें।',
      'join-community': 'समुदाय से जुड़ें',
      'feature-crop-calendar': 'फसल कैलेंडर',
      'feature-crop-calendar-desc': 'अनुकूल बुवाई और कटाई के समय के साथ अपनी कृषि गतिविधियों की योजना बनाएं।',
      'view-calendar': 'कैलेंडर देखें',
      'feature-learning-hub': 'सीखने का केंद्र',
      'feature-learning-hub-desc': 'अपने कृषि ज्ञान को बढ़ाने के लिए खेती गाइड, ट्यूटोरियल और सर्वोत्तम प्रथाओं तक पहुंचें।',
      'start-learning': 'सीखना शुरू करें',
      'feature-soil-testing': 'मिट्टी परीक्षण',
      'feature-soil-testing-desc': 'मिट्टी के स्वास्थ्य और फसल उत्पादकता में सुधार के लिए विस्तृत मिट्टी विश्लेषण और सिफारिशें प्राप्त करें।',
      'test-your-soil': 'अपनी मिट्टी की जांच करें',
      'feature-fertilizer-guide': 'उर्वरक गाइड',
      'feature-fertilizer-guide-desc': 'विभिन्न प्रकार के उर्वरकों, उनके उपयोग और विभिन्न फसलों के लिए आवेदन विधियों के बारे में जानें।',
      'view-guide': 'गाइड देखें',
      'feature-govt-schemes': 'सरकारी योजनाएं',
      'feature-govt-schemes-desc': 'किसानों के लिए उपलब्ध सरकारी कृषि योजनाओं और सब्सिडी की खोज करें और आवेदन करें।',
      'view-schemes': 'योजनाएं देखें',
      'feature-helplines': 'हेल्पलाइन',
      'feature-helplines-desc': 'तत्काल सहायता और समर्थन के लिए महत्वपूर्ण सरकारी और कृषि हेल्पलाइन नंबरों तक पहुंचें।',
      'view-helplines': 'हेल्पलाइन देखें',
      
      // How It Works Section
      'how-it-works-title': 'AgriSense कैसे काम करता है',
      'how-it-works-subtitle': 'एआई तकनीक के साथ अपनी खेती को बदलने के सरल चरण',
      'step-1-title': '1. अपना डेटा दर्ज करें',
      'step-1-desc': 'अपने खेत का स्थान, मिट्टी का प्रकार और अन्य प्रासंगिक पैरामीटर के बारे में विवरण दर्ज करें।',
      'step-2-title': '2. एआई विश्लेषण प्राप्त करें',
      'step-2-desc': 'हमारे उन्नत एल्गोरिदम आपके डेटा का विश्लेषण करके व्यक्तिगत सिफारिशें प्रदान करते हैं।',
      'step-3-title': '3. परिणाम प्राप्त करें',
      'step-3-desc': 'तुरंत व्यक्तिगत सिफारिशें प्राप्त करें।',
      'step-4-title': '4. बेहतर उत्पादन करें',
      'step-4-desc': 'अंतर्दृष्टि को लागू करें और अपनी उपज में सुधार देखें।',
      
      // Testimonials Section
      'testimonials-title': 'किसान क्या कहते हैं',
      'testimonials-subtitle': 'उन किसानों से सुनें जिन्होंने AgriSense के साथ अपनी खेती को बदल दिया है',
      'testimonial-1': '"AgriSense ने मेरी फसल की पैदावार में 30% की वृद्धि करने में मेरी मदद की। बीमारी का पता लगाने वाली सुविधा ने मेरी पूरी टमाटर की फसल को बचा लिया!"',
      'testimonial-2': '"बाजार मूल्य अपडेट और लाभ/हानि कैलकुलेटर ने मेरे कृषि व्यवसाय को बदल दिया है। अब मैं बेहतर निर्णय ले सकता हूं।"',
      'testimonial-3': '"एक नए किसान के रूप में, सीखने के संसाधन और समुदाय समर्थन अमूल्य रहे हैं। एआई सहायक मेरे सभी सवालों का तुरंत जवाब देता है।"',
      
      // CTA Section
      'cta-title': 'अपनी खेती को बदलने के लिए तैयार हैं?',
      'cta-subtitle': 'हजारों किसानों से जुड़ें जो पहले से ही एआई-संचालित कृषि अंतर्दृष्टि का लाभ उठा रहे हैं।',
      'get-started-button': 'अभी शुरू करें - यह मुफ़्त है! 🚀',
      'learn-more-button': 'और जानें',
      
      // Footer
      'footer-title': 'एग्रीसेंस',
      'footer-tagline': 'बेहतर उपज और टिकाऊ खेती के लिए एआई-संचालित कृषि समाधानों के साथ किसानों को सशक्त बनाना।',
      'quick-links': 'त्वरित लिंक',
      'contact-us': 'हमसे संपर्क करें',
      'email': 'ईमेल: support@agrisense.com',
      'phone': 'फोन: +91 98765 43210',
      'address': 'पता: 123 फार्म रोड, एग्री वैली, भारत',
      'copyright': '© 2023 एग्रीसेंस। सर्वाधिकार सुरक्षित।',
      'privacy-policy': 'गोपनीयता नीति',
      'terms-of-service': 'सेवा की शर्तें',
      
      // Common
      'home-title': 'एग्रीसेंस - होम',
      'offline-banner': '🌐 कम कनेक्टिविटी वाले क्षेत्रों में आंशिक रूप से ऑफलाइन काम करता है',
      'site-name': 'एग्रीसेंस',
      'site-tagline': 'एआई क्रॉप सिफारिश प्रणाली',
      
      // Helplines Page
      'helpline-title': 'किसान हेल्पलाइन नंबर',
      'helpline-subtitle': 'विभिन्न राज्यों के किसानों के लिए सरकारी हेल्पलाइन नंबर ढूंढें',
      'helpline-search': 'राज्य या नंबर से खोजें...',
      'helpline-kisan': 'किसान कॉल सेंटर',
      'helpline-state': 'राज्य कृषि विभाग',
      'helpline-select-state': 'एक राज्य चुनें...',
      'helpline-all-states': 'सभी राज्य',
      'community-hero-title': 'हमारे पौध प्रेमियों के समुदाय में शामिल हों',
      'start-discussion': 'नई चर्चा शुरू करें',
      'forum-title': 'किसान चर्चा मंच',
      'new-post': 'नया पोस्ट',
      'comments': 'टिप्पणियाँ',
      'likes': 'पसंद',
      'share': 'साझा करें',
      'view-details': 'विवरण देखें',
      'add-comment': 'एक टिप्पणी जोड़ें',
      'write-comment': 'टिप्पणी लिखें...',
      'translate': 'अनुवाद करें',
      'translating': 'अनुवाद हो रहा है...',
      'show-original': 'मूल दिखाएं',
      'hero-title': 'एआई द्वारा संचालित स्मार्ट खेती',
      'hero-subtitle': 'बुद्धिमान फसल सिफारिशों और रोग निदान के साथ कृषि में क्रांति',
      'cta-button': 'फसल सलाह प्राप्त करें 🌾',
      'features-title': 'हमारे एआई-संचालित समाधान',
      'features-subtitle': 'बेहतर उत्पादन और टिकाऊ खेती के लिए अत्याधुनिक तकनीक से किसानों को सशक्त बनाना',
      'crop-rec-title': 'एआई फसल सिफारिश',
      'disease-title': 'पौध रोग पहचान',
      'dashboard-title': 'कृषि डैशबोर्ड',
      'contact-title': 'संपर्क करें',
      'about-title': 'एग्रीसेंस के बारे में',
      'soil-hero-title': 'किफायती मिट्टी परीक्षण किट',
      'soil-hero-subtitle': 'स्मार्ट खेती के फैसलों के लिए अपनी मिट्टी को बेहतर जानें',
      'soil-cta-button': 'अभी अपनी किट का अनुरोध करें 📦',
      'soil-why-title': 'मिट्टी परीक्षण क्यों महत्वपूर्ण है?',
      'soil-whats-included': 'किट में क्या शामिल है?',
      'soil-request-title': 'अपनी मिट्टी परीक्षण किट का अनुरोध करें',
      'soil-request-subtitle': 'नीचे दिया गया फॉर्म भरें और हम 3-5 व्यावसायिक दिनों में किट आपके दरवाजे तक पहुंचा देंगे',
      
      // Profit & Loss Calculator
      'profit-loss-title': 'लाभ और हानि कैलकुलेटर',
      'profit-loss-subtitle': 'अपनी कृषि आय की गणना करें, खर्चों का विश्लेषण करें और बेहतर रिटर्न के लिए अपने कृषि व्यवसाय को अनुकूलित करें',
      'enter-details': 'अपनी खेती का विवरण दर्ज करें',
      'basic-info': 'मूल जानकारी',
      'crop-name': 'फसल का नाम',
      'land-area': 'भूमि क्षेत्रफल (एकड़)',
      'costs': 'लागत',
      'add-cost': 'लागत जोड़ें',
      'cost-name': 'लागत का नाम',
      'amount': 'राशि',
      'total-costs': 'कुल लागत',
      'revenue': 'आय',
      'add-revenue': 'आय जोड़ें',
      'revenue-name': 'आय स्रोत',
      'total-revenue': 'कुल आय',
      'calculate': 'गणना करें',
      'reset': 'रीसेट करें',
      'results': 'परिणाम',
      'profit': 'लाभ',
      'loss': 'हानि',
      'break-even': 'ब्रेक-ईवन',
      'profit-message': 'बहुत अच्छा! आपको लाभ हो रहा है',
      'loss-message': 'अपने खर्चों की समीक्षा करने पर विचार करें। आपका वर्तमान नुकसान है',
      'break-even-message': 'आपकी आपकी लागत के बराबर है। अपने लाभ मार्जिन को बढ़ाने के तरीकों पर विचार करें।',
      'per-acre': 'प्रति एकड़',
      'save-to-dashboard': 'डैशबोर्ड पर सहेजें',
      'print-report': 'रिपोर्ट प्रिंट करें',
      'saved-toast': 'आपके डैशबोर्ड पर सहेजा गया!',
      'error-toast': 'कृपया सभी आवश्यक फ़ील्ड भरें'
    },
    kn: {
      // Navigation
      'nav-home': 'ಮುಖ್ಯ',
      'nav-crop-rec': 'ಬೆಳೆ ಶಿಫಾರಸು',
      'nav-disease': 'ರೋಗ ಪತ್ತೆ',
      'nav-about': 'ಬಗ್ಗೆ',
      'nav-contact': 'ಸಂಪರ್ಕ',
      'nav-helplines': 'ಸಹಾಯಕ ಸಾಲುಗಳು',
      'nav-schemes': 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
      'nav-dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'nav-soil': 'ಮಣ್ಣು ಪರೀಕ್ಷಾ ಕಿಟ್',
      
      // Hero Section
      'hero-title': 'AI ನಿಂದ ಚಾಲಿತ ಸ್ಮಾರ್ಟ್ ಕೃಷಿ',
      'hero-subtitle': 'ಬುದ್ಧಿವಂತ ಬೆಳೆ ಶಿಫಾರಸುಗಳು ಮತ್ತು ರೋಗ ಪತ್ತೆಯೊಂದಿಗೆ ಕೃಷಿಯಲ್ಲಿ ಕ್ರಾಂತಿ',
      'cta-button': 'ಬೆಳೆ ಸಲಹೆ ಪಡೆಯಿರಿ 🌾',
      'soil-testing-button': 'ಮಣ್ಣು ಪರೀಕ್ಷಾ ಕಿಟ್ 🧪',
      
      // Stats Section
      'farmers-helped': 'ರೈತರಿಗೆ ಸಹಾಯ ಮಾಡಲಾಗಿದೆ',
      'crop-varieties': 'ಬೆಳೆ ವಿಧಗಳು',
      'accuracy-rate': 'ನಿಖರತೆ ದರ',
      'ai-support': 'AI ಬೆಂಬಲ',
      
      // Features Section
      'features-title': 'ನಮ್ಮ AI-ಚಾಲಿತ ಪರಿಹಾರಗಳು',
      'features-subtitle': 'ಉತ್ತಮ ಇಳುವರಿ ಮತ್ತು ಸುಸ್ಥಿರ ಕೃಷಿಗಾಗಿ ರೈತರನ್ನು ತಂತ್ರಜ್ಞಾನದೊಂದಿಗೆ ಸಶಕ್ತಗೊಳಿಸುವುದು',
      
      // Feature Cards
      'feature-crop-rec': 'ಬೆಳೆ ಶಿಫಾರಸು',
      'feature-crop-rec-desc': 'ನಿಮ್ಮ ಮಣ್ಣಿನ ನಿಯತಾಂಕಗಳು, ಹವಾಮಾನ ಪರಿಸ್ಥಿತಿಗಳು ಮತ್ತು ಪ್ರಾದೇಶಿಕ ಡೇಟಾವನ್ನು ಆಧರಿಸಿ AI-ಚಾಲಿತ ಬೆಳೆ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ.',
      'explore-feature': 'ವೈಶಿಷ್ಟ್ಯವನ್ನು ಅನ್ವೇಷಿಸಿ',
      'feature-disease-detection': 'ರೋಗ ಪತ್ತೆ',
      'feature-disease-desc': 'ಸುಧಾರಿತ ಕಂಪ್ಯೂಟರ್ ವಿಜನ್ ಬಳಸಿ ತ್ವರಿತ ರೋಗ ಗುರುತಿಸುವಿಕೆಗಾಗಿ ಸಸ್ಯ ಚಿತ್ರಗಳನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ಚಿಕಿತ್ಸಾ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ.',
      'detect-disease': 'ರೋಗವನ್ನು ಪತ್ತೆ ಮಾಡಿ',
      'feature-pest-detection': 'ಕೀಟ ಪತ್ತೆ',
      'feature-pest-desc': 'ಚಿತ್ರ ಗುರುತಿಸುವಿಕೆಯೊಂದಿಗೆ ನಿಮ್ಮ ಬೆಳೆಗಳನ್ನು ಪೀಡಿಸುವ ಸಾಮಾನ್ಯ ಕೀಟಗಳನ್ನು ಗುರುತಿಸಿ ಮತ್ತು ಸಾವಯವ ಮತ್ತು ರಾಸಾಯನಿಕ ಚಿಕಿತ್ಸಾ ಪರಿಹಾರಗಳನ್ನು ಪಡೆಯಿರಿ.',
      'feature-market-prices': 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
      'feature-market-prices-desc': 'ನಿಮ್ಮ ಉತ್ಪನ್ನಕ್ಕೆ ಉತ್ತಮ ಬೆಲೆ ಪಡೆಯಲು ಸಹಾಯ ಮಾಡುವ ವಿವಿಧ ಬೆಳೆಗಳ ನಿಜ-ಸಮಯದ ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು.',
      'check-prices': 'ಬೆಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
      'feature-profit-loss': 'ಲಾಭ/ನಷ್ಟ',
      'feature-profit-loss-desc': 'ನಿಮ್ಮ ಕೃಷಿ ವ್ಯವಹಾರವನ್ನು ಅನುಕೂಲಗೊಳಿಸಲು ನಿಮ್ಮ ಕೃಷಿ ಖರ್ಚುಗಳು ಮತ್ತು ಆದಾಯವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ಲಾಭ/ನಷ್ಟವನ್ನು ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ.',
      'calculate-now': 'ಈಗಲೇ ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ',
      'feature-ai-assistant': 'AI ಸಹಾಯಕ',
      'feature-ai-assistant-desc': 'ನಮ್ಮ 24/7 AI-ಚಾಲಿತ ಕೃಷಿ ಸಹಾಯಕದೊಂದಿಗೆ ನಿಮ್ಮ ಎಲ್ಲಾ ಕೃಷಿ ಪ್ರಶ್ನೆಗಳಿಗೆ ತ್ವರಿತ ಉತ್ತರಗಳನ್ನು ಪಡೆಯಿರಿ.',
      'chat-now': 'ಈಗಲೇ ಚಾಟ್ ಮಾಡಿ',
      'feature-community': 'ಸಮುದಾಯ',
      'feature-community-desc': 'ನಮ್ಮ ಕೃಷಿ ಸಮುದಾಯದಲ್ಲಿ ಇತರ ರೈತರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ, ಅನುಭವಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಿ ಮತ್ತು ತಜ್ಞರ ಸಲಹೆಗಳನ್ನು ಪಡೆಯಿರಿ.',
      'join-community': 'ಸಮುದಾಯವನ್ನು ಸೇರಿಕೊಳ್ಳಿ',
      'feature-crop-calendar': 'ಬೆಳೆ ಕ್ಯಾಲೆಂಡರ್',
      'feature-crop-calendar-desc': 'ಅನುಕೂಲಕರ ಬಿತ್ತನೆ ಮತ್ತು ಕೊಯ್ಲು ಸಮಯಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಕೃಷಿ ಚಟುವಟಿಕೆಗಳನ್ನು ಯೋಜಿಸಿ.',
      'view-calendar': 'ಕ್ಯಾಲೆಂಡರ್ ವೀಕ್ಷಿಸಿ',
      'feature-learning-hub': 'ಕಲಿಕಾ ಕೇಂದ್ರ',
      'feature-learning-hub-desc': 'ನಿಮ್ಮ ಕೃಷಿ ಜ್ಞಾನವನ್ನು ಹೆಚ್ಚಿಸಲು ಕೃಷಿ ಮಾರ್ಗದರ್ಶಿಗಳು, ಟ್ಯುಟೋರಿಯಲ್‌ಗಳು ಮತ್ತು ಉತ್ತಮ ಅಭ್ಯಾಸಗಳನ್ನು ಪ್ರವೇಶಿಸಿ.',
      'start-learning': 'ಕಲಿಯಲು ಪ್ರಾರಂಭಿಸಿ',
      'feature-soil-testing': 'ಮಣ್ಣು ಪರೀಕ್ಷೆ',
      'feature-soil-testing-desc': 'ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಮತ್ತು ಬೆಳೆ ಉತ್ಪಾದಕತೆಯನ್ನು ಸುಧಾರಿಸಲು ವಿವರವಾದ ಮಣ್ಣು ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ.',
      'test-your-soil': 'ನಿಮ್ಮ ಮಣ್ಣನ್ನು ಪರೀಕ್ಷಿಸಿ',
      'feature-fertilizer-guide': 'ಗೊಬ್ಬರ ಮಾರ್ಗದರ್ಶಿ',
      'feature-fertilizer-guide-desc': 'ವಿವಿಧ ರೀತಿಯ ಗೊಬ್ಬರಗಳು, ಅವುಗಳ ಬಳಕೆಗಳು ಮತ್ತು ವಿವಿಧ ಬೆಳೆಗಳಿಗೆ ಅನ್ವಯಿಸುವ ವಿಧಾನಗಳ ಬಗ್ಗೆ ತಿಳಿಯಿರಿ.',
      'view-guide': 'ಮಾರ್ಗದರ್ಶಿ ವೀಕ್ಷಿಸಿ',
      'feature-govt-schemes': 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
      'feature-govt-schemes-desc': 'ರೈತರಿಗೆ ಲಭ್ಯವಿರುವ ಸರ್ಕಾರಿ ಕೃಷಿ ಯೋಜನೆಗಳು ಮತ್ತು ಸಬ್ಸಿಡಿಗಳನ್ನು ಅನ್ವೇಷಿಸಿ ಮತ್ತು ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.',
      'view-schemes': 'ಯೋಜನೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
      'feature-helplines': 'ಸಹಾಯಕ ಸಾಲುಗಳು',
      'feature-helplines-desc': 'ತ್ವರಿತ ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲಕ್ಕಾಗಿ ಪ್ರಮುಖ ಸರ್ಕಾರಿ ಮತ್ತು ಕೃಷಿ ಸಹಾಯಕ ಸಾಲು ಸಂಖ್ಯೆಗಳನ್ನು ಪ್ರವೇಶಿಸಿ.',
      'view-helplines': 'ಸಹಾಯಕ ಸಾಲುಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
      
      // How It Works Section
      'how-it-works-title': 'AgriSense ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
      'how-it-works-subtitle': 'AI ತಂತ್ರಜ್ಞಾನದೊಂದಿಗೆ ನಿಮ್ಮ ಕೃಷಿಯನ್ನು ರೂಪಾಂತರಿಸಲು ಸರಳ ಹಂತಗಳು',
      'step-1-title': '1. ನಿಮ್ಮ ಡೇಟಾವನ್ನು ನಮೂದಿಸಿ',
      'step-1-desc': 'ನಿಮ್ಮ ಕೃಷಿ ಭೂಮಿಯ ಸ್ಥಳ, ಮಣ್ಣಿನ ಪ್ರಕಾರ ಮತ್ತು ಇತರ ಸಂಬಂಧಿತ ನಿಯತಾಂಕಗಳ ಬಗ್ಗೆ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ.',
      'step-2-title': '2. AI ವಿಶ್ಲೇಷಣೆ ಪಡೆಯಿರಿ',
      'step-2-desc': 'ನಮ್ಮ ಸುಧಾರಿತ ಅಲ್ಗಾರಿದಮ್‌ಗಳು ವೈಯಕ್ತಿಕ ಶಿಫಾರಸುಗಳನ್ನು ಒದಗಿಸಲು ನಿಮ್ಮ ಡೇಟಾವನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತವೆ.',
      'step-3-title': '3. ಫಲಿತಾಂಶಗಳನ್ನು ಪಡೆಯಿರಿ',
      'step-3-desc': 'ತಕ್ಷಣವೇ ವೈಯಕ್ತಿಕ ಶಿಫಾರಸುಗಳನ್ನು ಸ್ವೀಕರಿಸಿ.',
      'step-4-title': '4. ಉತ್ತಮವಾಗಿ ಬೆಳೆಯಿರಿ',
      'step-4-desc': 'ಒಳನೋಟಗಳನ್ನು ಅನುಷ್ಠಾನಗೊಳಿಸಿ ಮತ್ತು ನಿಮ್ಮ ಇಳುವರಿ ಹೇಗೆ ಸುಧಾರಿಸುತ್ತದೆ ಎಂದು ನೋಡಿ.',
      
      // Testimonials Section
      'testimonials-title': 'ರೈತರು ಏನು ಹೇಳುತ್ತಾರೆ',
      'testimonials-subtitle': 'AgriSense ನೊಂದಿಗೆ ತಮ್ಮ ಕೃಷಿಯನ್ನು ರೂಪಾಂತರಿಸಿದ ರೈತರಿಂದ ಕೇಳಿ',
      'testimonial-1': '"AgriSense ನಿಮ್ಮ ಶಿಫಾರಸುಗಳೊಂದಿಗೆ ನನ್ನ ಬೆಳೆ ಇಳುವರಿಯನ್ನು 30% ಹೆಚ್ಚಿಸಲು ನನಗೆ ಸಹಾಯ ಮಾಡಿದೆ. ರೋಗ ಪತ್ತೆ ವೈಶಿಷ್ಟ್ಯವು ನನ್ನ ಸಂಪೂರ್ಣ ಟೊಮೇಟೊ ಬೆಳೆಯನ್ನು ಉಳಿಸಿತು!"',
      'testimonial-2': '"ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ನವೀಕರಣಗಳು ಮತ್ತು ಲಾಭ/ನಷ್ಟ ಕ್ಯಾಲ್ಕುಲೇಟರ್ ನನ್ನ ಕೃಷಿ ವ್ಯವಹಾರಕ್ಕೆ ಗೇಮ್-ಚೇಂಜರ್‌ಗಳಾಗಿವೆ. ಈಗ ನಾನು ಉತ್ತಮ ನಿರ್ಧಾರಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಬಲ್ಲೆ."',
      'testimonial-3': '"ಹೊಸ ರೈತನಾಗಿ, ಕಲಿಕಾ ಸಂಪನ್ಮೂಲಗಳು ಮತ್ತು ಸಮುದाय ಬೆಂಬಲ ಅಮೂಲ್ಯವಾಗಿವೆ. AI ಸಹಾಯಕನು ನನ್ನ ಎಲ್ಲಾ ಪ್ರಶ್ನೆಗಳಿಗೂ ತಕ್ಷಣ ಉತ್ತರಿಸುತ್ತಾನೆ."',
      
      // CTA Section
      'cta-title': 'ನಿಮ್ಮ ಕೃಷಿಯನ್ನು ರೂಪಾಂತರಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಾ?',
      'cta-subtitle': 'ಈಗಾಗಲೇ AI-ಚಾಲಿತ ಕೃಷಿ ಒಳನೋಟಗಳಿಂದ ಪ್ರಯೋಜನ ಪಡೆಯುತ್ತಿರುವ ಸಾವಿರಾರು ರೈತರಿಗೆ ಸೇರಿಕೊಳ್ಳಿ.',
      'get-started-button': 'ಈಗಲೇ ಪ್ರಾರಂಭಿಸಿ - ಇದು ಉಚಿತ! 🚀',
      'learn-more-button': 'ಹೆಚ್ಚು ತಿಳಿಯಿರಿ',
      
      // Footer
      'footer-title': 'ಆಗ್ರಿಸೆನ್ಸ್',
      'footer-tagline': 'ಉತ್ತಮ ಇಳುವರಿ ಮತ್ತು ಸುಸ್ಥಿರ ಕೃಷಿಗಾಗಿ AI-ಚಾಲಿತ ಕೃಷಿ ಪರಿಹಾರಗಳೊಂದಿಗೆ ರೈತರನ್ನು ಸಶಕ್ತಗೊಳಿಸುವುದು.',
      'quick-links': 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
      'contact-us': 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
      'email': 'ಇಮೇಲ್: support@agrisense.com',
      'phone': 'ಫೋನ್: +91 98765 43210',
      'address': 'ವಿಳಾಸ: 123 ಫಾರ್ಮ್ ರೋಡ್, ಆಗ್ರಿ ವ್ಯಾಲಿ, ಭಾರತ',
      'copyright': '© 2023 ಆಗ್ರಿಸೆನ್ಸ್. ಎಲ್ಲ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
      'privacy-policy': 'ಗೋಪ್ಯತಾ ನೀತಿ',
      'terms-of-service': 'ಸೇವಾ ನಿಯಮಗಳು',
      
      // Common
      'home-title': 'ಆಗ್ರಿಸೆನ್ಸ್ - ಮುಖಪುಟ',
      'offline-banner': '🌐 ಕಡಿಮೆ ಸಂಪರ್ಕದ ಪ್ರದೇಶಗಳಲ್ಲಿ ಭಾಗಶಃ ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ',
      'site-name': 'ಆಗ್ರಿಸೆನ್ಸ್',
      'site-tagline': 'AI ಬೆಳೆ ಶಿಫಾರಸು ವ್ಯವಸ್ಥೆ',
      
      // Helplines Page
      'helpline-title': 'ರೈತರ ಸಹಾಯಕ ಸಾಲು ಸಂಖ್ಯೆಗಳು',
      'helpline-subtitle': 'ವಿವಿಧ ರಾಜ್ಯಗಳ ರೈತರಿಗಾಗಿ ಸರ್ಕಾರಿ ಸಹಾಯಕ ಸಾಲು ಸಂಖ್ಯೆಗಳನ್ನು ಹುಡುಕಿ',
      'helpline-search': 'ರಾಜ್ಯ ಅಥವಾ ಸಂಖ್ಯೆಯಿಂದ ಹುಡುಕಿ...',
      'helpline-kisan': 'ಕಿಸಾನ್ ಕಾಲ್ ಸೆಂಟರ್',
      'helpline-state': 'ರಾಜ್ಯ ಕೃಷಿ ಇಲಾಖೆ',
      'helpline-select-state': 'ಒಂದು ರಾಜ್ಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ...',
      'helpline-all-states': 'ಎಲ್ಲಾ ರಾಜ್ಯಗಳು',
      'community-hero-title': 'ನಮ್ಮ ಸಸ್ಯಪ್ರೇಮಿಗಳ ಸಮುದಾಯವನ್ನು ಸೇರಿ',
      'start-discussion': 'ಹೊಸ ಚರ್ಚೆ ಪ್ರಾರಂಭಿಸಿ',
      'forum-title': 'ರೈತರ ಚರ್ಚಾ ವೇದಿಕೆ',
      'new-post': 'ಹೊಸ ಪೋಸ್ಟ್',
      'comments': 'ಟಿಪ್ಪಣಿಗಳು',
      'likes': 'ಇಷ್ಟ',
      'share': 'ಹಂಚಿಕೊಳ್ಳಿ',
      'view-details': 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
      'add-comment': 'ಕಾಮೆಂಟ್ ಸೇರಿಸಿ',
      'write-comment': 'ಕಾಮೆಂಟ್ ಬರೆಯಿರಿ...',
      'translate': 'ಭಾಷಾಂತರಿಸಿ',
      'translating': 'ಭಾಷಾಂತರಿಸಲಾಗುತ್ತಿದೆ...',
      'show-original': 'ಮೂಲ ತೋರಿಸಿ',
      'hero-title': 'AI ನಿಂದ ಚಾಲಿತ ಸ್ಮಾರ್ಟ್ ಕೃಷಿ',
      'hero-subtitle': ' ಬೆಳೆ ಶಿಫಾರಸುಗಳು ಮತ್ತು ರೋಗ ಪತ್ತೆಯೊಂದಿಗೆ ಕೃಷಿಯಲ್ಲಿ ಕ್ರಾಂತಿ',
      'cta-button': 'ಬೆಳೆ ಸಲಹೆ ಪಡೆಯಿರಿ 🌾',
      'features-title': 'ನಮ್ಮ AI-ಚಾಲಿತ ಪರಿಹಾರಗಳು',
      'features-subtitle': 'ಉತ್ತಮ ಇಳುವರಿ ಮತ್ತು ಸುಸ್ಥಿರ ಕೃಷಿಗಾಗಿ ರೈತರನ್ನು ತಂತ್ರಜ್ಞಾನದಿಂದ ಸಬಲೀಕರಿಸುವುದು',
      'crop-rec-title': 'AI ಬೆಳೆ ಶಿಫಾರಸು',
      'disease-title': 'ಸಸ್ಯ ರೋಗ ಪತ್ತೆ',
      'dashboard-title': 'ಕೃಷಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'contact-title': 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
      'about-title': 'ಆಗ್ರಿಸೆನ್ಸ್ ಬಗ್ಗೆ',
      'soil-hero-title': 'ಕೈಗೆಟಕುವ ದರದಲ್ಲಿ ಮಣ್ಣು ಪರೀಕ್ಷಾ ಕಿಟ್',
      'soil-hero-subtitle': 'ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ನಿರ್ಧಾರಗಳಿಗಾಗಿ ನಿಮ್ಮ ಮಣ್ಣನ್ನು ಚೆನ್ನಾಗಿ ತಿಳಿದುಕೊಳ್ಳಿ',
      'soil-cta-button': 'ಈಗಲೇ ನಿಮ್ಮ ಕಿಟ್ ಅನ್ನು ವಿನಂತಿಸಿ 📦',
      'soil-why-title': 'ಮಣ್ಣು ಪರೀಕ್ಷೆ ಏಕೆ ಮುಖ್ಯ?',
      'soil-whats-included': 'ಕಿಟ್‌ನಲ್ಲಿ ಏನಿದೆ?',
      'soil-request-title': 'ನಿಮ್ಮ ಮಣ್ಣಿನ ಪರೀಕ್ಷಾ ಕಿಟ್ ಅನ್ನು ವಿನಂತಿಸಿ',
      'soil-request-subtitle': 'ಕೆಳಗಿನ ಫಾರ್ಮ್ ಅನ್ನು ಭರ್ತಿ ಮಾಡಿ ಮತ್ತು ನಾವು 3-5 ವ್ಯವಹಾರ ದಿನಗಳಲ್ಲಿ ಕಿಟ್ ಅನ್ನು ನಿಮ್ಮ ಬಾಗಿಲಿಗೆ ತಲುಪಿಸುತ್ತೇವೆ',
      
      // Profit & Loss Calculator
      'profit-loss-title': 'ಲಾಭ ಮತ್ತು ನಷ್ಟ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
      'profit-loss-subtitle': 'ನಿಮ್ಮ ಕೃಷಿ ಲಾಭವನ್ನು ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ, ಖರ್ಚುಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ ಮತ್ತು ಉತ್ತಮ ಆದಾಯಕ್ಕಾಗಿ ನಿಮ್ಮ ಕೃಷಿ ವ್ಯವಹಾರವನ್ನು ಅನುಕೂಲಗೊಳಿಸಿ',
      'enter-details': 'ನಿಮ್ಮ ಕೃಷಿ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ',
      'basic-info': 'ಮೂಲ ಮಾಹಿತಿ',
      'crop-name': 'ಬೆಳೆಯ ಹೆಸರು',
      'land-area': 'ಭೂಮಿಯ ವಿಸ್ತೀರ್ಣ (ಎಕರೆ)',
      'costs': 'ಖರ್ಚುಗಳು',
      'add-cost': 'ಖರ್ಚು ಸೇರಿಸಿ',
      'cost-name': 'ಖರ್ಚಿನ ಹೆಸರು',
      'amount': 'ಮೊತ್ತ',
      'total-costs': 'ಒಟ್ಟು ಖರ್ಚು',
      'revenue': 'ಆದಾಯ',
      'add-revenue': 'ಆದಾಯ ಸೇರಿಸಿ',
      'revenue-name': 'ಆದಾಯದ ಮೂಲ',
      'total-revenue': 'ಒಟ್ಟು ಆದಾಯ',
      'calculate': 'ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ',
      'reset': 'ಮರುಹೊಂದಿಸಿ',
      'results': 'ಫಲಿತಾಂಶಗಳು',
      'profit': 'ಲಾಭ',
      'loss': 'ನಷ್ಟ',
      'break-even': 'ಬ್ರೇಕ್-ಈವನ್',
      'profit-message': 'ಅದ್ಭುತ! ನೀವು ಲಾಭ ಗಳಿಸುತ್ತಿದ್ದೀರಿ',
      'loss-message': 'ನಿಮ್ಮ ಖರ್ಚುಗಳನ್ನು ಪರಿಶೀಲಿಸುವುದನ್ನು ಪರಿಗಣಿಸಿ. ನಿಮ್ಮ ಪ್ರಸ್ತುತ ನಷ್ಟ',
      'break-even-message': 'ನಿಮ್ಮ ಆದಾಯವು ನಿಮ್ಮ ಖರ್ಚುಗಳಿಗೆ ಸಮಾನವಾಗಿದೆ. ನಿಮ್ಮ ಲಾಭದ ಅಂಶವನ್ನು ಹೆಚ್ಚಿಸುವ ಮಾರ್ಗಗಳನ್ನು ಪರಿಗಣಿಸಿ.',
      'per-acre': 'ಪ್ರತಿ ಎಕರೆಗೆ',
      'save-to-dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಉಳಿಸಿ',
      'print-report': 'ರಿಪೋರ್ಟ್ ಮುದ್ರಿಸಿ',
      'saved-toast': 'ನಿಮ್ಮ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಉಳಿಸಲಾಗಿದೆ!',
      'error-toast': 'ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಅಗತ್ಯವಾದ ಫೀಲ್ಡ್‌ಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ'
    }
  };

  const storageKey = 'agrisense_lang';
  let currentLanguage = localStorage.getItem(storageKey) || 'en';

  function translatePage(lang) {
    const dict = translations[lang] || translations.en;
    document.querySelectorAll('[data-translate]').forEach(el => {
      const key = el.getAttribute('data-translate');
      if (dict[key]) {
        el.textContent = dict[key];
      }
    });
  }

  function initLanguage() {
    const select = document.getElementById('languageSelect');
    if (select) {
      select.value = currentLanguage;
      select.addEventListener('change', function () {
        currentLanguage = this.value;
        localStorage.setItem(storageKey, currentLanguage);
        translatePage(currentLanguage);
      });
    }
    translatePage(currentLanguage);
  }

  document.addEventListener('DOMContentLoaded', initLanguage);
})();
